Projet-chat-final/config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  #Team
  resources :team
  #ressources pour les produits dans le panier
  resources :line_items

  #resources pours les paniers
  resources :carts, only: [:new, :create, :destroy, :show]

  #resources pour les produits
  resources :products

  #resources for admin
  resources :admin, only: [:new, :create, :destroy]

  #resources for user_session
  resources :session

  #creationuser
  resources :user do
  	resources :message , only: [ :new , :index , :destroy , :create , :edit , :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Projet-chat-final/app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

Projet-chat-final/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Projet-chat-final/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product, currentuser)
    item = line_items.find_by(product: product, current_user_id: currentuser)

    if item
      item.quantity += 1
    else
      item = line_items.new(product: product, current_user_id: currentuser)
    end
    item
  end
  
  def total
    line_items.to_a.sum(&:total)
  end
end

Projet-chat-final/app/models/checkout.rb
class Checkout < ApplicationRecord
end

Projet-chat-final/app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total
    product.price * quantity
  end

end

Projet-chat-final/app/models/message.rb
class Message < ApplicationRecord
	validates :contenu, presence: true
	belongs_to :user
end

Projet-chat-final/app/models/payer.rb
class Payer < ApplicationRecord
end

Projet-chat-final/app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :nullify
end

Projet-chat-final/app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :messages
end

Projet-chat-final/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def new; end

  def create
     admin_input_email = params[:email]
     admin_input_password = params[:password]

    puts admin = Admin.find_by(email: admin_input_email)

    if admin && admin.authenticate(admin_input_password)
      # puts "tafiditra"
      session[:admin_id] = admin.id
      redirect_to products_path

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:admin_id)
    redirect_to root_path
  end
end

Projet-chat-final/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
    @in_checkout = Checkout.all

  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @@a = Checkout.all
    #debut cart
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { }#redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end

      @amount = "500" #params[:total_price].to_s
      # puts "***************#{@amount}"
      @checkout = Checkout.create(cart_id: params[:cart_id], total_price: params[:total_price], user_id: params[:user_id])
      # puts "*************#{params[:cart_id]}"
      # puts "*******************#{params[:total_price]}"
      # puts "***********************#{params[:user_id]}"
      @checkout.save
      #stripe
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })

      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @amount,
        description: 'Rails Stripe customer',
        currency: 'usd',
      })

      @@a.each do |a|
        # puts "************#{a.cart_id}"
        # puts "************#{a.total_price}"
        # puts "************#{a.user_id}"
        if current_user.id == a.user_id
          @cart_id_last = a.cart_id
          @current_user_last = a.user_id
          @current_total_last_to_pay = a.total_price
        end
      end
      # puts "********************#{@cart_id_last}"
      # puts "************************#{@current_user_last}"
      # puts "****************************#{@current_total_last_to_pay}"
      # puts "*******************************#{customer.id}"
      # puts "**********************************#{params[:stripeEmail]}"
      # puts "************************************#{params[:stripeToken]}"

      @payer = Payer.create(cart_id: @cart_id_last, current_user_id: @current_user_last,
        total_to_pay: @current_total_last_to_pay, customer_id: customer.id, custumer_email: params[:stripeEmail],
        token: params[:stripeToken])

      @payer.save

    rescue Stripe::CardError => e
      flash[:error] = e.message
      @cart.destroy
      session.delete(:cart_id)
      redirect_to new_cart_path
    end
  end


  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    session.delete(:cart_id)

    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #only for specified current_user
    def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

Projet-chat-final/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_product, only: [:show]

  # GET /products
  # GET /products.json
  def index
    # @products = Product.order(:title)
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url)
    end
end

Projet-chat-final/app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

Projet-chat-final/app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
  end

  def create

  	puts '*' * 100

  	User.create(nom: params[:Nom] , prenom: params[:Prenom] , age: params[:Age] , email: params[:Email] , password: params[:password])
  	redirect_to '/session/new'
  end
end

Projet-chat-final/app/helpers/admin_helper.rb
module AdminHelper
  def current_admin
    Admin.find_by(id: session[:admin_id])
 end

  def log_in(admin)
    session[:admin_id] = admin.id
 end
end

Projet-chat-final/app/helpers/application_helper.rb
module ApplicationHelper
end

Projet-chat-final/app/helpers/carts_helper.rb
module CartsHelper
end

Projet-chat-final/app/helpers/charges_helper.rb
module ChargesHelper
end

Projet-chat-final/app/helpers/line_items_helper.rb
module LineItemsHelper
end

Projet-chat-final/app/helpers/page_helper.rb
module PageHelper

end

Projet-chat-final/app/helpers/products_helper.rb
module ProductsHelper
end

Projet-chat-final/app/helpers/session_helper.rb
module SessionHelper

  def current_user
    User.find_by(id: session[:id])
  end

  def log_in(user)
   session[:user_id] = user.id
  end

end

Projet-chat-final/app/helpers/user_helper.rb
module UserHelper
end

Projet-chat-final/app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Projet-chat-final/app/views/carts/create.html.erb
<h2>Thanks, you paid cat!</h2>
  <%= link_to 'Home', root_path, class: "btn btn-danger btn-sm" %>

Projet-chat-final/app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

Projet-chat-final/app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

Projet-chat-final/app/views/carts/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style >
      body{
        margin:0;
        padding:0;
      }
    </style>
  </head>
  <body>

    <%= form_tag carts_path do %>
    <div class="card text-center">
      <div class="card-header">
        Sayna SAKA Payment
      </div>
      <div class="card-body">
        <%@in_checkout.each do |checkout|%>
          <% if(checkout.user_id == current_user.id) %>
            <% @totaux = checkout.total_price %><%end%>
          <%end%>
          <h5 class="card-title"><%=current_user.prenom%>
            vous devez payer :
          </h5>
          <p class="card-text">
            <b><%=@totaux%></b>
            MGA</p>
        <%end%>
        <a>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="CHAT" data-amount="<%=@totaux%>" data-currency="MGA" data-locale="auto"></script>
        </a>
      </div>
      <div class="card-footer text-muted">
        Mandoa Vola
      </div>
    </div>
  </body>
</html>

Projet-chat-final/app/views/carts/show.html.erb
<!-- <ul> <''% @cart.line_items.each do |item|%> <''%if(item.current_user_id == current_user.id)%> <li><''%= item.product.title %> (x<''%=item.quantity%>)</li> <''%end%> <''%end%> <''%=current_user.id%> </ul> -->
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style>
      body{
        margin:0;
        padding:0;
      }
    </style>
  </head>
  <body>

    <ul class="list-group">
      <button type="button" class="list-group-item list-group-item-action active">
        <h4>Mon Panier de saka</h4>
      </button>
      <% @cart.line_items.each do |item|%>
        <% @c_user = item.current_user_id%>
          <%if(item.current_user_id == current_user.id)%>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= item.product.title %>
              (x<%=item.quantity%>)
              <span class="badge badge-primary badge-pill"><%= number_to_currency(item.total, unit: "MGA ", separator: ",", format: "%u%n")%></span>
            </li>
          <%end%>
        <%end%>
        <% if (@c_user == current_user.id)%>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <b>Total :</b>
            <span class="badge badge-primary badge-pill"><%= number_to_currency(@cart.total, unit: "MGA ", separator: ",", format: "%u%n")%></span>
          </li>
        <%end%>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <%= link_to 'Miverina Hividy saka', root_path, class: "btn btn-primary btn-sm" %><br><br>
          <%= button_to 'Vider le panier', @cart, method: :delete, data: { confirm: "Tena alana ao anaty sobika le saka.?"}, class: "btn btn-danger btn-sm" %><br><br>
          <%= button_to 'Check Out', {:controller => "carts", :action => "create",:cart_id => session[:cart_id], :total_price => @cart.total, :user_id=> current_user.id,}, :method=>:post, class: "btn btn-danger btn-sm" %>
        </li>
      </ul>
    </body>
  </html>

Projet-chat-final/app/views/user/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style media="screen">
		body{
			background-color:#222F3E;
		}
		p{
			color:white;
			font-size:40px;
		}
		label{
			color:white;
		}
	</style>

	<link rel="stylesheet" type="text/css" href="/create.css">
	<link rel="stylesheet" type="text/css" href="/bootstrap.min.css">

</head>



<body class="bgimg w3-display-container" >

<div class="container">

   <p class="logo" >Sign<span class="spa">Up</span></p>



  <form class="form-horizontal"  action="/user" method="POST">
  	<!-- tsy adino ilay action sy method -->

		  	<input name="authenticity_token" type="hidden"  value="<%= form_authenticity_token %>">
		  	<!-- manala ilay authenticy error -->

		    <div class="form-group">
		      <label class="control-label">Nom:</label>
		      <div class="col-sm-10">
		        <input type="text" class="form-control col-md-4 col-sm-12 " name="Nom" placeholder="Entrez votre Nom">
		      </div>
		    </div>

		    <div class="form-group">
		      <label class="control-label">Prenom:</label>
		      <div class="col-sm-10">
		        <input type=text" class="form-control col-md-4 col-sm-12 " name="Prenom" placeholder="Entrez votre Prenom">
		      </div>
		    </div>

		    <div class="form-group">
		      <label class="control-label">Age:</label>
		      <div class="col-sm-10">
		        <input type="text" class="form-control col-md-4 col-sm-12"  name="Age" placeholder="Enter votre Age">
		      </div>
		    </div>

		    <div class="form-group">
		      <label class="control-label">Email:</label>
		      <div class="col-sm-10">
		        <input type="email" class="form-control col-md-4 col-sm-12" name="Email" placeholder="Enter email">
		      </div>
		    </div>

		    <div class="form-group">
		      <label class="control-label">Password:</label>
		      <div class="col-sm-10">
		        <input type="password" class="form-control col-md-4 col-sm-12" name="password" placeholder="Enter password">
		      </div>
		    </div>

         <div class="btn" >
         	<div class="form-group">
		      <div class="col-sm-offset-2  col-sm-10">
		        <button id="btn" type="submit" class="btn btn-success">S'inscrire</button>
		      </div>
		    </div>
         </div>


  </form>

</div>
</body>


</html>