Projet-chat-final/config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  #Team
  resources :team
  #ressources pour les produits dans le panier
  resources :line_items

  #resources pours les paniers
  resources :carts, only: [:new, :create, :destroy, :show]

  #resources pour les produits
  resources :products

  #resources for admin
  resources :admin, only: [:new, :create, :destroy]

  #resources for user_session
  resources :session

  #creationuser
  resources :user do
  	resources :message , only: [ :new , :index , :destroy , :create , :edit , :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Projet-chat-final/app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

Projet-chat-final/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Projet-chat-final/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product, currentuser)
    item = line_items.find_by(product: product, current_user_id: currentuser)

    if item
      item.quantity += 1
    else
      item = line_items.new(product: product, current_user_id: currentuser)
    end
    item
  end
  
  def total
    line_items.to_a.sum(&:total)
  end
end

Projet-chat-final/app/models/checkout.rb
class Checkout < ApplicationRecord
end

Projet-chat-final/app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total
    product.price * quantity
  end

end

Projet-chat-final/app/models/message.rb
class Message < ApplicationRecord
	validates :contenu, presence: true
	belongs_to :user
end

Projet-chat-final/app/models/payer.rb
class Payer < ApplicationRecord
end

Projet-chat-final/app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :nullify
end

Projet-chat-final/app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :messages
end

Projet-chat-final/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def new; end

  def create
     admin_input_email = params[:email]
     admin_input_password = params[:password]

    puts admin = Admin.find_by(email: admin_input_email)

    if admin && admin.authenticate(admin_input_password)
      # puts "tafiditra"
      session[:admin_id] = admin.id
      redirect_to products_path

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:admin_id)
    redirect_to root_path
  end
end

Projet-chat-final/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_product, only: [:show]

  # GET /products
  # GET /products.json
  def index
    # @products = Product.order(:title)
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url)
    end
end

Projet-chat-final/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #authenticate_admin
    def authenticate_admin
      unless current_admin
        flash[:danger] = "Please log in."
        redirect_to root_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url)
    end
end

Projet-chat-final/app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

Projet-chat-final/app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
  end

  def create

  	puts '*' * 100

  	User.create(nom: params[:Nom] , prenom: params[:Prenom] , age: params[:Age] , email: params[:Email] , password: params[:password])
  	redirect_to '/session/new'
  end
end

Projet-chat-final/app/helpers/admin_helper.rb
module AdminHelper
  def current_admin
    Admin.find_by(id: session[:admin_id])
 end

  def log_in(admin)
    session[:admin_id] = admin.id
 end
end

Projet-chat-final/app/helpers/application_helper.rb
module ApplicationHelper
end

Projet-chat-final/app/helpers/carts_helper.rb
module CartsHelper
end

Projet-chat-final/app/helpers/charges_helper.rb
module ChargesHelper
end

Projet-chat-final/app/helpers/line_items_helper.rb
module LineItemsHelper
end

Projet-chat-final/app/helpers/page_helper.rb
module PageHelper

end

Projet-chat-final/app/helpers/products_helper.rb
module ProductsHelper
end

Projet-chat-final/app/helpers/session_helper.rb
module SessionHelper

  def current_user
    User.find_by(id: session[:id])
  end

  def log_in(user)
   session[:user_id] = user.id
  end

end

Projet-chat-final/app/helpers/user_helper.rb
module UserHelper
end

Projet-chat-final/app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field form-group">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field form-group">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions form-group">
    <%= form.submit %>
  </div>
<% end %>

Projet-chat-final/app/views/products/edit.html.erb
<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

Projet-chat-final/app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
			body{
				background-color:#222F3E;
			}
			p{
				color:white;
				font-size:40px;
			}
			td, th, h1{
				color:white;
        padding-left:15px;
			}

      h1{
        padding-left:50px;
      }
		</style>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'bootstrap' %>
  </head>
  <body>
    <h1>Products</h1>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Price</th>
          <th>Image url</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.title %></td>
            <td><%= truncate strip_tags(product.description), length: 130 %></td>
            <td><%= product.price %></td>
            <td><%= product.image_url %></td>
            <td><%= link_to 'Show', product, class:"btn btn-primary", width:"10px"%></td>
            <td><%= link_to 'Edit', edit_product_path(product), class:"btn btn-success", width:"10px" %></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger", width:"10px" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Product', new_product_path, class:"btn btn-primary" %>

  </body>
</html>
<p id="notice"><%= notice %></p>

Projet-chat-final/app/views/products/new.html.erb
<!-- <h1>New Product</h1> <é%= render 'form', product: @product %> <é%= link_to 'Back', products_path %> -->
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
			body{
				background-color:#222F3E;
			}
			p{
				color:white;
				font-size:40px;
			}
			td, th, h1{
				color:white;
        padding-left:15px;
			}

      h1 {
        font-weight: bold;
      }


		</style>
  </head>
  <body>

<center><h1>New Cat</h1></center>
    <div class="container">
      <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
          <div id="admin" class="card card-signin my-5">
            <div class="card-body ">

              <form action="/products" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="Sac12jW8NRSCP7uUj536XKHFWMI/DI1oh1buLAxh65IFhHyoe2R4ncLzKKJ0Jk9wZDkG8ZIcVxChIw5B/wVBfw==">

                <div class="field form-label-group ">
                  <label for="product_title">Title</label>
                  <input class="form-control" type="text" name="product[title]" id="product_title">
                </div>

                <div class="field form-label-group ">
                  <label for="product_description">Description</label>
                  <textarea class="form-control" name="product[description]" id="product_description"></textarea>
                </div>

                <div class="field form-label-group ">
                  <label for="product_price">Price</label>
                  <input class="form-control" type="number" name="product[price]" id="product_price">
                </div>

                <div class="field form-label-group ">
                  <label for="product_image_url">Image url</label>
                  <input class="form-control" type="text" name="product[image_url]" id="product_image_url"><br>
                </div>

                <div class="actions form-label-group ">
                  <input class="form-control btn btn-success" type="submit" name="commit" value="Create Product" data-disable-with="Create Product">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

Projet-chat-final/app/views/products/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>


  <style media="screen">
    body{
      background-color:#222F3E;
    }
    p{
      color:white;
      font-size:20px;
    }
    td, th, h1{
      color:white;
      padding-left:15px;
    }

    a {
      color:cyan;
    }


  </style>



  <body>


    <p id="notice"><%= notice %></p>

    <p>
      <strong>Title:</strong>
      <%= @product.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @product.description %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @product.price %>
    </p>

    <p>
      <strong>Image url:</strong>
      <%= @product.image_url %>
    </p>

    <%= link_to 'Edit', edit_product_path(@product), class:"btn btn-success" %> |
    <%= link_to 'Back', products_path , class:"btn btn-secondary" %>


  </body>
</html>