Projet-chat-final/config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  #Team
  resources :team
  #ressources pour les produits dans le panier
  resources :line_items

  #resources pours les paniers
  resources :carts, only: [:new, :create, :destroy, :show]

  #resources pour les produits
  resources :products

  #resources for admin
  resources :admin, only: [:new, :create, :destroy]

  #resources for user_session
  resources :session

  #creationuser
  resources :user do
  	resources :message , only: [ :new , :index , :destroy , :create , :edit , :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Projet-chat-final/app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

Projet-chat-final/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Projet-chat-final/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product, currentuser)
    item = line_items.find_by(product: product, current_user_id: currentuser)

    if item
      item.quantity += 1
    else
      item = line_items.new(product: product, current_user_id: currentuser)
    end
    item
  end
  
  def total
    line_items.to_a.sum(&:total)
  end
end

Projet-chat-final/app/models/checkout.rb
class Checkout < ApplicationRecord
end

Projet-chat-final/app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total
    product.price * quantity
  end

end

Projet-chat-final/app/models/message.rb
class Message < ApplicationRecord
	validates :contenu, presence: true
	belongs_to :user
end

Projet-chat-final/app/models/payer.rb
class Payer < ApplicationRecord
end

Projet-chat-final/app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :nullify
end

Projet-chat-final/app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :messages
end

Projet-chat-final/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_product, only: [:show]

  # GET /products
  # GET /products.json
  def index
    # @products = Product.order(:title)
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url)
    end
end

Projet-chat-final/app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

Projet-chat-final/app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
  end

  def create

  	puts '*' * 100

  	User.create(nom: params[:Nom] , prenom: params[:Prenom] , age: params[:Age] , email: params[:Email] , password: params[:password])
  	redirect_to '/session/new'
  end
end

Projet-chat-final/app/helpers/admin_helper.rb
module AdminHelper
  def current_admin
    Admin.find_by(id: session[:admin_id])
 end

  def log_in(admin)
    session[:admin_id] = admin.id
 end
end

Projet-chat-final/app/helpers/application_helper.rb
module ApplicationHelper
end

Projet-chat-final/app/helpers/carts_helper.rb
module CartsHelper
end

Projet-chat-final/app/helpers/charges_helper.rb
module ChargesHelper
end

Projet-chat-final/app/helpers/line_items_helper.rb
module LineItemsHelper
end

Projet-chat-final/app/helpers/page_helper.rb
module PageHelper

end

Projet-chat-final/app/helpers/products_helper.rb
module ProductsHelper
end

Projet-chat-final/app/helpers/session_helper.rb
module SessionHelper

  def current_user
    User.find_by(id: session[:id])
  end

  def log_in(user)
   session[:user_id] = user.id
  end

end

Projet-chat-final/app/helpers/user_helper.rb
module UserHelper
end

Projet-chat-final/app/views/home/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title></title>

    <!-- <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/carousel/"> -->

    <!-- Bootstrap core CSS -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
      #image {
        border-radius: 25px;
      }

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      /*footer*/

      footer {
        background-color: #1e272e;

        padding-bottom: 100px;
      }

      h3 {
        color: #485460;
      }

      #titre {
        color: white;
        font-size: 20px;
        font-weight: bold;

        padding: 10px 0;
      }

      #logo {
        width: 60px;
        height: 40px;
        margin-bottom: 10px;
      }

      #mail {
        padding-top: 35px;
      }

      #paye {
        margin-top: 100px;
      }

      #foot {
        padding-top: 200px;
      }

      #link {
        width: 35px;
        height: 35px;
      }

      #lien {
        color: #353b48;
      }

      #logo-footer {
        padding-bottom: 10px;

      }

      #logos {
        padding-top: 100px;
      }

      #logo-footer2 {
        }
    </style>
    <!-- Custom styles for this template -->

  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Sayna<span style="color:#d35400 ; padding:60px 0px"><b>SAKA</b></span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <% if(current_user) %>
                <!-- <a class="nav-link" href="/session/<""%= @id %>" data-method="delete" >Log Out</a> -->
                <%= link_to "Log Out", session_path(current_user.id), method: :delete, class: 'nav-link' %>

              <%else%>
                <a class="nav-link" href=<%= new_session_path %>>Log In</a>
              <%end%>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%=team_index_path%>">Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%=new_admin_path%>">Admin</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>

    <main role="main">
      <!--Carousel Wrapper-->
      <div id="carousel-example-2" class="carousel slide carousel-fade" data-ride="carousel">
        <!--Indicators-->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-2" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-2" data-slide-to="1"></li>
          <li data-target="#carousel-example-2" data-slide-to="2"></li>
        </ol>
        <!--/.Indicators-->
        <!--Slides-->
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <div class="view">
              <img class="d-block w-100" src="/sary/po.jpg" alt="First slide" width="1600px" height="550px">
              <div class="mask rgba-black-light"></div>
            </div>
            <div class="carousel-caption">
              <h2 class="h3-responsive" style="color:brown">Varotra Saka en ligne</h2>
              <p style="color:brown">Offre tena tsara</p>
            </div>
          </div>
          <div class="carousel-item">
            <!--Mask color-->
            <div class="view">
              <img class="d-block w-100" src="sary/ljk.jpeg" alt="Second slide" width="1600px" height="550px">
              <div class="mask rgba-black-strong"></div>
            </div>
            <div class="carousel-caption">
              <h2 class="h3-responsive" style="color:cyan">Varotra Saka en ligne</h2>
              <p style="color:brown">Qualité de service au top</p>
            </div>
          </div>
          <div class="carousel-item">
            <!--Mask color-->
            <div class="view">
              <img class="d-block w-100" src="sary/cvb.jpg" alt="Third slide" width="1600px" height="550px">
              <div class="mask rgba-black-slight"></div>
            </div>
            <div class="carousel-caption">
              <h2 class="h3-responsive">Varotra Saka en ligne</h2>
              <p>Misy garantie</p>
            </div>
          </div>
        </div>
        <!--/.Slides-->
        <!--Controls-->
        <a class="carousel-control-prev" href="#carousel-example-2" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel-example-2" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
        <!--/.Controls-->
      </div>
      <!--/.Carousel Wrapper-->

      <!-- <div id="myCarousel" class="carousel slide" data-ride="carousel"> <ol class="carousel-indicators"> <li data-target="#myCarousel" data-slide-to="0" class="active"></li> <li data-target="#myCarousel" data-slide-to="1"></li> <li
      data-target="#myCarousel" data-slide-to="2"></li> </ol> <div class="carousel-inner"> <div class="carousel-item active"> <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice"
      focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg> <div class="container"> <div class="carousel-caption text-left"> <h1>Example headline.</h1> <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id
      elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p> <p> <a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a> </p> </div> </div> </div> <div class="carousel-item"> <svg
      class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg> <div class="container"> <div
      class="carousel-caption"> <h1>Another example headline.</h1> <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p> <p> <a
      class="btn btn-lg btn-primary" href="#" role="button">Learn more</a> </p> </div> </div> </div> <div class="carousel-item"> <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid
      slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg> <div class="container"> <div class="carousel-caption text-right"> <h1>One more for good measure.</h1> <p>Cras justo odio, dapibus ac facilisis in, egestas eget
      quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p> <p> <a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a> </p> </div> </div> </div> </div> <a
      class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#myCarousel"
      role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a> </div> -->

      <!-- Marketing messaging and featurettes ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
          <!-- /.col-lg-4 -->
          <!-- /.col-lg-4 -->
          <% @products.each do |product| %>
            <div class="col-lg-4">
              <!-- <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"> <title></title><rect width="100%"
              height="100%" fill="#777"/> <text x="50%" y="50%" fill="#777" dy=".3em">140x140</text> </svg> -->
              <p ><%= image_tag product.image_url,id:"image", width: 200 %></p>
              <h3><%= product.title %></h3>
              <p><%= truncate strip_tags(product.description), length: 75 %></p>
              <p>
                <a href="#"><%= number_to_currency product.price, unit: "MGA ", separator: ",", format: "%u%n" %></a>&nbsp
                <% if(current_user) %>
                  <a><%= button_to 'Ajouter au panier', line_items_path(product_id: product), class: "btn btn-primary" %></a>
                <%else%>
                  <a><%= link_to 'Ajouter au panier', new_session_path, class: "btn btn-primary" %></a>
                <%end%>
                <!-- <a><é%= link_to 'show', data-toggle:"modal" class: "btn btn-success" %></a> -->

                <!-- <a class="btn btn-secondary" href="#" role="button">View details &raquo;</a> -->
              </p>
            </div>
          <%end%>
          <!-- /.col-lg-4 -->
        </div>
        <!--MODAL -->
        <!-- Modal show -->

        <!--MODAL -->
        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

      </div>
      <!-- /.container -->

      <!-- FOOTER -->
      <footer class="container-fluid" style="background-color:#7f8c8d ; padding-top:100px ; padding-bottom:100px">

        <!-- Footer Text -->
        <div class="container-fluid text-center text-md-left">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <!-- <div class="col-md-6 mt-md-0 mt-3"> <!-- Content <h5 class="text-uppercase font-weight-bold">Footer text 1</h5> <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita sapiente sint, nulla, nihil repudiandae commodi voluptatibus
            corrupti animi sequi aliquid magnam debitis, maxime quam recusandae harum esse fugiat. Itaque, culpa?</p> </div> -->
            <div class="col-md-6 mt-md-0 mt-3">
              <h3 style="text-align:center"><b style="color:black">Mode de payement</b></h3>
              <div id="paye" class="row">

                <div class="col-md-3">
                  <img id="logo" src="/logo/bit.png">
                </div>

                <div class="col-md-3">
                  <img id="logo" src="/logo/mvola.png">
                </div>

                <div class="col-md-3">
                  <img id="logo" src="/logo/paypal.png">
                </div>

                <div class="col-md-3">
                  <img id="logo" src="/logo/index.png">
                </div>

              </div>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none pb-3">

            <!-- Grid column -->
            <div class="col-md-6 mb-md-0 mb-3">

              <!-- Content -->
              <h5 class="text-uppercase font-weight-bold" style="text-align:center"><b style="color:black">Contact</b></h5>
              <br>
              <p style="text-align:center">Mail : sakanay@milay.com</p>
              <p style="text-align:center">Tel : +261 30 12 00 00</p>
              <p style="text-align:center">Adresse : @tranosaka faravohitra</p>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Footer Text -->

        <!-- Copyright --><br><br>
        <div class="footer-copyright text-center py-3">© 2019 Copyright:
          <a href="#">
            saynasaka.com</a>
        </div>
        <!-- Copyright -->

        <!-- Footer -->
      </footer>
    </main>
  </html>

Projet-chat-final/app/views/team/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
	<meta charset="utf-8">
	<title></title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application' %>
	<%= stylesheet_pack_tag 'bootstrap' %>

	<style >
		body{
			background-color:#34495E;
		}
		p{
			color:white;
		}
		img{
			box-shadow:0px 5px 1px 3px black;

		}
		h2{
			color:black;
		}
		h5{
			color:cyan;
		}
	</style>

</head>

<body>
	<header>
		<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
			<a class="navbar-brand" href="#">Sayna<span style="color:#d35400 ; padding:60px 0px"><b>SAKA</b></span></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a class="nav-link" href="/">Home
							<span class="sr-only">(current)</span></a>
					</li>
				</ul>
				<form class="form-inline mt-2 mt-md-0">
					<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form>
			</div>
		</nav>
	</header>

	<!--  -->
	<!-- Section: Team v.1 -->
<section class="team-section text-center my-5">

  <!-- Section heading -->
  <h2 class="h1-responsive font-weight-bold my-5">Our amazing team</h2>
  <!-- Section description -->
  <p class="grey-text w-responsive mx-auto mb-5">Izahay dia mpivarotra saka belouha</p>

  <!-- Grid row -->
  <div class="row">

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6 mb-lg-0 mb-5">
      <div class="avatar mx-auto">
        <img src="/img/p1.jpeg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">Jo</h5>
      <p class="text-uppercase blue-text"><strong>#sayna@4</strong></p>
      <p class="grey-text">Sed ut perspiciatis unde omnis iste natus error sit voluptatem ipsa accusantium
        doloremque rem laudantium totam aperiam.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Twitter -->
        <a class="p-2 fa-lg tw-ic">
          <i class="fab fa-twitter blue-text"> </i>
        </a>
        <!-- Instagram -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-instagram blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6 mb-lg-0 mb-5">
      <div class="avatar mx-auto">
        <img src="/img/p2.jpeg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">Jean</h5>
      <p class="text-uppercase blue-text"><strong>#sayna@4</strong></p>
      <p class="grey-text">Sed ut perspiciatis unde omnis iste natus error sit voluptatem ipsa accusantium
        doloremque rem laudantium totam aperiam.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Instagram -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-instagram blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6 mb-md-0 mb-5">
      <div class="avatar mx-auto">
        <img src="/img/p3.jpeg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">Rasit</h5>
      <p class="text-uppercase blue-text"><strong>#sayna@4</strong></p>
      <p class="grey-text">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
        mollit anim est fugiat nulla id eu laborum.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Instagram -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-instagram blue-text"> </i>
        </a>
        <!-- Dribbble -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-dribbble blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-3 col-md-6">
      <div class="avatar mx-auto">
        <img src="/img/p4.jpeg" class="rounded-circle z-depth-1"
          alt="Sample avatar">
      </div>
      <h5 class="font-weight-bold mt-4 mb-3">Mirindra</h5>
      <p class="text-uppercase blue-text"><strong>#sayna@4</strong></p>
      <p class="grey-text">Perspiciatis repellendus ad odit consequuntur, eveniet earum nisi qui consectetur
        totam officia voluptates perferendis voluptatibus aut.</p>
      <ul class="list-unstyled mb-0">
        <!-- Facebook -->
        <a class="p-2 fa-lg fb-ic">
          <i class="fab fa-facebook-f blue-text"> </i>
        </a>
        <!-- Github -->
        <a class="p-2 fa-lg ins-ic">
          <i class="fab fa-github blue-text"> </i>
        </a>
      </ul>
    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->

</section>
<!-- Section: Team v.1 -->
	<!--  -->

</body>

</html>