Projet-chat-final/config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  #Team
  resources :team
  #ressources pour les produits dans le panier
  resources :line_items

  #resources pours les paniers
  resources :carts, only: [:new, :create, :destroy, :show]

  #resources pour les produits
  resources :products

  #resources for admin
  resources :admin, only: [:new, :create, :destroy]

  #resources for user_session
  resources :session

  #creationuser
  resources :user do
  	resources :message , only: [ :new , :index , :destroy , :create , :edit , :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Projet-chat-final/app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

Projet-chat-final/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Projet-chat-final/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product, currentuser)
    item = line_items.find_by(product: product, current_user_id: currentuser)

    if item
      item.quantity += 1
    else
      item = line_items.new(product: product, current_user_id: currentuser)
    end
    item
  end
  
  def total
    line_items.to_a.sum(&:total)
  end
end

Projet-chat-final/app/models/checkout.rb
class Checkout < ApplicationRecord
end

Projet-chat-final/app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total
    product.price * quantity
  end

end

Projet-chat-final/app/models/message.rb
class Message < ApplicationRecord
	validates :contenu, presence: true
	belongs_to :user
end

Projet-chat-final/app/models/payer.rb
class Payer < ApplicationRecord
end

Projet-chat-final/app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :nullify
end

Projet-chat-final/app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :messages
end

Projet-chat-final/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def new; end

  def create
     admin_input_email = params[:email]
     admin_input_password = params[:password]

    puts admin = Admin.find_by(email: admin_input_email)

    if admin && admin.authenticate(admin_input_password)
      # puts "tafiditra"
      session[:admin_id] = admin.id
      redirect_to products_path

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:admin_id)
    redirect_to root_path
  end
end

Projet-chat-final/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_product, only: [:show]

  # GET /products
  # GET /products.json
  def index
    # @products = Product.order(:title)
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url)
    end
end

Projet-chat-final/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
     product =  Product.find(params[:product_id])
     currentuser = current_user.id
    # puts "current puts is #{product.title}"
    # @line_item = @cart.line_items.new(product: product, current_user_id: current_user.id)
      @line_item = @cart.add_product(product, currentuser)
     # puts "current user is #{current_user.id}"
     # puts "current user is #{currentuser}"
    respond_to do |format|
      if @line_item.save
        # puts "current puts is #{@line_item.current_user_id}"
        format.html { redirect_to @line_item.cart, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:cart_id, :product_id, :quantity)
    end
end

Projet-chat-final/app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

Projet-chat-final/app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
  end

  def create

  	puts '*' * 100

  	User.create(nom: params[:Nom] , prenom: params[:Prenom] , age: params[:Age] , email: params[:Email] , password: params[:password])
  	redirect_to '/session/new'
  end
end

Projet-chat-final/app/helpers/admin_helper.rb
module AdminHelper
  def current_admin
    Admin.find_by(id: session[:admin_id])
 end

  def log_in(admin)
    session[:admin_id] = admin.id
 end
end

Projet-chat-final/app/helpers/application_helper.rb
module ApplicationHelper
end

Projet-chat-final/app/helpers/carts_helper.rb
module CartsHelper
end

Projet-chat-final/app/helpers/charges_helper.rb
module ChargesHelper
end

Projet-chat-final/app/helpers/line_items_helper.rb
module LineItemsHelper
end

Projet-chat-final/app/helpers/page_helper.rb
module PageHelper

end

Projet-chat-final/app/helpers/products_helper.rb
module ProductsHelper
end

Projet-chat-final/app/helpers/session_helper.rb
module SessionHelper

  def current_user
    User.find_by(id: session[:id])
  end

  def log_in(user)
   session[:user_id] = user.id
  end

end

Projet-chat-final/app/helpers/user_helper.rb
module UserHelper
end

Projet-chat-final/app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Projet-chat-final/app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

Projet-chat-final/app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Cart</th>
      <th>Product</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.cart %></td>
        <td><%= line_item.product %></td>
        <td><%= line_item.quantity %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

Projet-chat-final/app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

Projet-chat-final/app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>